### ISSUE TITLE
Code origin

### ISSUE THREAD

**Issue by odinhg** [AnhTuan160301/Traffic-Forecasting_-Graph-Neural-Network#1]
Why are you copying my repository and posting it without citing the original source, instead of creating a fork?

It appears that all you did was to change the README.md file.

**Comment by AnhTuan160301** [comment]
Dear Odin,
I am so sorry about this. I am just practicing writing and reading code to
understand the graph network. I am really new to Github and I don't know if
I 'm bothering you. I will delete this repository. I assure you that this
is used for research learning purposes, not for any business or any purpose
of making money.
Thank you for your reminder and sorry about this

Best regards,
Tuan.

Vào Th 5, 8 thg 8, 2024 vào lúc 21:15 Odin Hoff Gardå <
***@***.***> đã viết:
